name: 'publish'

on:
  push:
    branches:
      - release

jobs:
  publish:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin'
            build_command: 'build:mac'
          - platform: 'macos-latest'
            args: '--target x86_64-apple-darwin'
            build_command: 'build:mac'
          - platform: 'ubuntu-22.04'
            args: ''
            build_command: 'build:linux'
          - platform: 'windows-latest'
            args: ''
            build_command: 'build:win'

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v6.0.2

      - name: Install Node
        uses: actions/setup-node@v6.3.0
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install
      
      - name: Build app
        run: npm run ${{ matrix.build_command }}