name: 'publish'

on:
  push:
    branches:
      - release

jobs:
  publish:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin'
            build_command: 'build:mac'
          - platform: 'macos-latest'
            args: '--target x86_64-apple-darwin'
            build_command: 'build:mac'
          - platform: 'ubuntu-22.04'
            args: ''
            build_command: 'build:linux'
          - platform: 'windows-latest'
            args: ''
            build_command: 'build:win'

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v6.0.2

      - name: Install Node
        uses: actions/setup-node@v6.3.0
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install
      
      - name: Get version
        id: version
        run: echo "VERSION=v$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
      
      - name: Build app
        run: npm run ${{ matrix.build_command }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v7.0.1
        with:
          name: ${{ matrix.platform }}-${{ matrix.args || 'default' }}
          path: |
            dist/*.exe
            dist/*.dmg
            dist/*.AppImage
            dist/*.deb
            dist/*.rpm
            dist/*.snap
            dist/*.zip
            dist/*.blockmap
            dist/latest*.yml

  create-release:
    needs: publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v8.0.1
        with:
          path: artifacts
      
      - name: Get version
        id: version
        run: echo "VERSION=v$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
      
      - name: Create Release
        uses: softprops/action-gh-release@v3.0.0
        with:
          files: artifacts/**/*
          generate_release_notes: true
          tag_name: ${{ steps.version.outputs.VERSION }}
          name: ${{ steps.version.outputs.VERSION }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}